<?php

namespace Database\Seeders;

use App\Models\Kabupaten;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $date = Carbon::now()->format('Y-m-d H:i:s');
        $kabupaten = [
            ['provinsi_id' =>'1','name'=>'KABUPATEN SIMEULUE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH SINGKIL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH TENGGARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH BESAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN PIDIE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN BIREUEN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH BARAT DAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN GAYO LUES','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH TAMIANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN NAGAN RAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN ACEH JAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN BENER MERIAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KABUPATEN PIDIE JAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KOTA BANDA ACEH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KOTA SABANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KOTA LANGSA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KOTA LHOKSEUMAWE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'1','name'=>'KOTA SUBULUSSALAM','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN NIAS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN MANDAILING NATAL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN TAPANULI SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN TAPANULI TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN TAPANULI UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN TOBA SAMOSIR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN LABUHAN BATU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN ASAHAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN SIMALUNGUN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN DAIRI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN KARO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN DELI SERDANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN LANGKAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN NIAS SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN HUMBANG HASUNDUTAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN PAKPAK BHARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN SAMOSIR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN SERDANG BEDAGAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN BATU BARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN PADANG LAWAS UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN PADANG LAWAS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN LABUHAN BATU SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN LABUHAN BATU UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN NIAS UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KABUPATEN NIAS BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KOTA SIBOLGA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KOTA TANJUNG BALAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KOTA PEMATANG SIANTAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KOTA TEBING TINGGI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KOTA MEDAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KOTA BINJAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KOTA PADANGSIDIMPUAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'2','name'=>'KOTA GUNUNGSITOLI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN KEPULAUAN MENTAWAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN PESISIR SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN SOLOK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN SIJUNJUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN TANAH DATAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN PADANG PARIAMAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN AGAM','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN LIMA PULUH KOTA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN PASAMAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN SOLOK SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN DHARMASRAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KABUPATEN PASAMAN BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KOTA PADANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KOTA SOLOK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KOTA SAWAH LUNTO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KOTA PADANG PANJANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KOTA BUKITTINGGI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KOTA PAYAKUMBUH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'3','name'=>'KOTA PARIAMAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN KUANTAN SINGINGI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN INDRAGIRI HULU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN INDRAGIRI HILIR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN PELALAWAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN S I A K','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN KAMPAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN ROKAN HULU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN BENGKALIS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN ROKAN HILIR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KABUPATEN KEPULAUAN MERANTI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KOTA PEKANBARU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'4','name'=>'KOTA D U M A I','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN KERINCI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN MERANGIN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN SAROLANGUN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN BATANG HARI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN MUARO JAMBI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN TANJUNG JABUNG TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN TANJUNG JABUNG BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN TEBO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KABUPATEN BUNGO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KOTA JAMBI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'5','name'=>'KOTA SUNGAI PENUH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN OGAN KOMERING ULU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN OGAN KOMERING ILIR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN MUARA ENIM','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN LAHAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN MUSI RAWAS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN MUSI BANYUASIN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN BANYU ASIN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN OGAN KOMERING ULU SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN OGAN KOMERING ULU TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN OGAN ILIR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN EMPAT LAWANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN PENUKAL ABAB LEMATANG ILIR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KABUPATEN MUSI RAWAS UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KOTA PALEMBANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KOTA PRABUMULIH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KOTA PAGAR ALAM','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'6','name'=>'KOTA LUBUKLINGGAU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN BENGKULU SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN REJANG LEBONG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN BENGKULU UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN KAUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN SELUMA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN MUKOMUKO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN LEBONG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN KEPAHIANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KABUPATEN BENGKULU TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'7','name'=>'KOTA BENGKULU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN LAMPUNG BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN TANGGAMUS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN LAMPUNG SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN LAMPUNG TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN LAMPUNG TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN LAMPUNG UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN WAY KANAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN TULANGBAWANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN PESAWARAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN PRINGSEWU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN MESUJI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN TULANG BAWANG BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KABUPATEN PESISIR BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KOTA BANDAR LAMPUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'8','name'=>'KOTA METRO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'9','name'=>'KABUPATEN BANGKA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'9','name'=>'KABUPATEN BELITUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'9','name'=>'KABUPATEN BANGKA BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'9','name'=>'KABUPATEN BANGKA TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'9','name'=>'KABUPATEN BANGKA SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'9','name'=>'KABUPATEN BELITUNG TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'9','name'=>'KOTA PANGKAL PINANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'10','name'=>'KABUPATEN KARIMUN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'10','name'=>'KABUPATEN BINTAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'10','name'=>'KABUPATEN NATUNA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'10','name'=>'KABUPATEN LINGGA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'10','name'=>'KABUPATEN KEPULAUAN ANAMBAS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'10','name'=>'KOTA B A T A M','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'10','name'=>'KOTA TANJUNG PINANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'11','name'=>'KABUPATEN KEPULAUAN SERIBU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'11','name'=>'KOTA JAKARTA SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'11','name'=>'KOTA JAKARTA TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'11','name'=>'KOTA JAKARTA PUSAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'11','name'=>'KOTA JAKARTA BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'11','name'=>'KOTA JAKARTA UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN BOGOR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN SUKABUMI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN CIANJUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN BANDUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN GARUT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN TASIKMALAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN CIAMIS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN KUNINGAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN CIREBON','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN MAJALENGKA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN SUMEDANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN INDRAMAYU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN SUBANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN PURWAKARTA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN KARAWANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN BEKASI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN BANDUNG BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KABUPATEN PANGANDARAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA BOGOR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA SUKABUMI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA BANDUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA CIREBON','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA BEKASI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA DEPOK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA CIMAHI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA TASIKMALAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'12','name'=>'KOTA BANJAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN CILACAP','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN BANYUMAS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN PURBALINGGA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN BANJARNEGARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN KEBUMEN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN PURWOREJO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN WONOSOBO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN MAGELANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN BOYOLALI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN KLATEN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN SUKOHARJO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN WONOGIRI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN KARANGANYAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN SRAGEN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN GROBOGAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN BLORA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN REMBANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN PATI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN KUDUS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN JEPARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN DEMAK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN SEMARANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN TEMANGGUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN KENDAL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN BATANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN PEKALONGAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN PEMALANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN TEGAL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KABUPATEN BREBES','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KOTA MAGELANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KOTA SURAKARTA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KOTA SALATIGA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KOTA SEMARANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KOTA PEKALONGAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'13','name'=>'KOTA TEGAL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'14','name'=>'KABUPATEN KULON PROGO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'14','name'=>'KABUPATEN BANTUL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'14','name'=>'KABUPATEN GUNUNG KIDUL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'14','name'=>'KABUPATEN SLEMAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'14','name'=>'KOTA YOGYAKARTA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN PACITAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN PONOROGO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN TRENGGALEK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN TULUNGAGUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN BLITAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN KEDIRI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN MALANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN LUMAJANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN JEMBER','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN BANYUWANGI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN BONDOWOSO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN SITUBONDO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN PROBOLINGGO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN PASURUAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN SIDOARJO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN MOJOKERTO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN JOMBANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN NGANJUK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN MADIUN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN MAGETAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN NGAWI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN BOJONEGORO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN TUBAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN LAMONGAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN GRESIK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN BANGKALAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN SAMPANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN PAMEKASAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KABUPATEN SUMENEP','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA KEDIRI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA BLITAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA MALANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA PROBOLINGGO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA PASURUAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA MOJOKERTO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA MADIUN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA SURABAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'15','name'=>'KOTA BATU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'16','name'=>'KABUPATEN PANDEGLANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'16','name'=>'KABUPATEN LEBAK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'16','name'=>'KABUPATEN TANGERANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'16','name'=>'KABUPATEN SERANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'16','name'=>'KOTA TANGERANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'16','name'=>'KOTA CILEGON','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'16','name'=>'KOTA SERANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'16','name'=>'KOTA TANGERANG SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KABUPATEN JEMBRANA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KABUPATEN TABANAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KABUPATEN BADUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KABUPATEN GIANYAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KABUPATEN KLUNGKUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KABUPATEN BANGLI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KABUPATEN KARANG ASEM','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KABUPATEN BULELENG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'17','name'=>'KOTA DENPASAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KABUPATEN LOMBOK BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KABUPATEN LOMBOK TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KABUPATEN LOMBOK TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KABUPATEN SUMBAWA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KABUPATEN DOMPU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KABUPATEN BIMA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KABUPATEN SUMBAWA BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KABUPATEN LOMBOK UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KOTA MATARAM','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'18','name'=>'KOTA BIMA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN SUMBA BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN SUMBA TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN KUPANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN TIMOR TENGAH SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN TIMOR TENGAH UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN BELU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN ALOR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN LEMBATA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN FLORES TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN SIKKA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN ENDE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN NGADA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN MANGGARAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN ROTE NDAO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN MANGGARAI BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN SUMBA TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN SUMBA BARAT DAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN NAGEKEO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN MANGGARAI TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN SABU RAIJUA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KABUPATEN MALAKA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'19','name'=>'KOTA KUPANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN SAMBAS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN BENGKAYANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN LANDAK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN MEMPAWAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN SANGGAU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN KETAPANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN SINTANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN KAPUAS HULU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN SEKADAU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN MELAWI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN KAYONG UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KABUPATEN KUBU RAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KOTA PONTIANAK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'20','name'=>'KOTA SINGKAWANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN KOTAWARINGIN BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN KOTAWARINGIN TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN KAPUAS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN BARITO SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN BARITO UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN SUKAMARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN LAMANDAU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN SERUYAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN KATINGAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN PULANG PISAU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN GUNUNG MAS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN BARITO TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KABUPATEN MURUNG RAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'21','name'=>'KOTA PALANGKA RAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN TANAH LAUT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN KOTA BARU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN BANJAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN BARITO KUALA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN TAPIN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN HULU SUNGAI SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN HULU SUNGAI TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN HULU SUNGAI UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN TABALONG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN TANAH BUMBU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KABUPATEN BALANGAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KOTA BANJARMASIN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'22','name'=>'KOTA BANJAR BARU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KABUPATEN PASER','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KABUPATEN KUTAI BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KABUPATEN KUTAI KARTANEGARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KABUPATEN KUTAI TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KABUPATEN BERAU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KABUPATEN PENAJAM PASER UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KABUPATEN MAHAKAM HULU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KOTA BALIKPAPAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KOTA SAMARINDA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'23','name'=>'KOTA BONTANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'24','name'=>'KABUPATEN MALINAU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'24','name'=>'KABUPATEN BULUNGAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'24','name'=>'KABUPATEN TANA TIDUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'24','name'=>'KABUPATEN NUNUKAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'24','name'=>'KOTA TARAKAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN BOLAANG MONGONDOW','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN MINAHASA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN KEPULAUAN SANGIHE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN KEPULAUAN TALAUD','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN MINAHASA SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN MINAHASA UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN BOLAANG MONGONDOW UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN SIAU TAGULANDANG BIARO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN MINAHASA TENGGARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN BOLAANG MONGONDOW SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KABUPATEN BOLAANG MONGONDOW TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KOTA MANADO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KOTA BITUNG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KOTA TOMOHON','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'25','name'=>'KOTA KOTAMOBAGU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN BANGGAI KEPULAUAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN BANGGAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN MOROWALI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN POSO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN DONGGALA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN TOLI-TOLI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN BUOL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN PARIGI MOUTONG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN TOJO UNA-UNA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN SIGI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN BANGGAI LAUT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KABUPATEN MOROWALI UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'26','name'=>'KOTA PALU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN KEPULAUAN SELAYAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN BULUKUMBA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN BANTAENG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN JENEPONTO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN TAKALAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN GOWA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN SINJAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN MAROS','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN PANGKAJENE DAN KEPULAUAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN BARRU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN BONE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN SOPPENG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN WAJO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN SIDENRENG RAPPANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN PINRANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN ENREKANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN LUWU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN TANA TORAJA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN LUWU UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN LUWU TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KABUPATEN TORAJA UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KOTA MAKASSAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KOTA PAREPARE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'27','name'=>'KOTA PALOPO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN BUTON','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN MUNA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN KONAWE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN KOLAKA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN KONAWE SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN BOMBANA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN WAKATOBI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN KOLAKA UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN BUTON UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN KONAWE UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN KOLAKA TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN KONAWE KEPULAUAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN MUNA BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN BUTON TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KABUPATEN BUTON SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KOTA KENDARI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'28','name'=>'KOTA BAUBAU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'29','name'=>'KABUPATEN BOALEMO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'29','name'=>'KABUPATEN GORONTALO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'29','name'=>'KABUPATEN POHUWATO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'29','name'=>'KABUPATEN BONE BOLANGO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'29','name'=>'KABUPATEN GORONTALO UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'29','name'=>'KOTA GORONTALO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'30','name'=>'KABUPATEN MAJENE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'30','name'=>'KABUPATEN POLEWALI MANDAR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'30','name'=>'KABUPATEN MAMASA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'30','name'=>'KABUPATEN MAMUJU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'30','name'=>'KABUPATEN MAMUJU UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'30','name'=>'KABUPATEN MAMUJU TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN MALUKU TENGGARA BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN MALUKU TENGGARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN MALUKU TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN BURU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN KEPULAUAN ARU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN SERAM BAGIAN BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN SERAM BAGIAN TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN MALUKU BARAT DAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KABUPATEN BURU SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KOTA AMBON','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'31','name'=>'KOTA TUAL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KABUPATEN HALMAHERA BARAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KABUPATEN HALMAHERA TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KABUPATEN KEPULAUAN SULA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KABUPATEN HALMAHERA SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KABUPATEN HALMAHERA UTARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KABUPATEN HALMAHERA TIMUR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KABUPATEN PULAU MOROTAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KABUPATEN PULAU TALIABU','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KOTA TERNATE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'32','name'=>'KOTA TIDORE KEPULAUAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN FAKFAK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN KAIMANA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN TELUK WONDAMA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN TELUK BINTUNI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN MANOKWARI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN SORONG SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN SORONG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN RAJA AMPAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN TAMBRAUW','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN MAYBRAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN MANOKWARI SELATAN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KABUPATEN PEGUNUNGAN ARFAK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'33','name'=>'KOTA SORONG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN MERAUKE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN JAYAWIJAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN JAYAPURA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN NABIRE','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN KEPULAUAN YAPEN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN BIAK NUMFOR','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN PANIAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN PUNCAK JAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN MIMIKA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN BOVEN DIGOEL','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN MAPPI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN ASMAT','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN YAHUKIMO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN PEGUNUNGAN BINTANG','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN TOLIKARA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN SARMI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN KEEROM','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN WAROPEN','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN SUPIORI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN MAMBERAMO RAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN NDUGA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN LANNY JAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN MAMBERAMO TENGAH','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN YALIMO','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN PUNCAK','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN DOGIYAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN INTAN JAYA','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KABUPATEN DEIYAI','created_at' => $date,'updated_at' => $date],
            ['provinsi_id' =>'34','name'=>'KOTA JAYAPURA','created_at' => $date,'updated_at' => $date]
        ];
        Kabupaten::insert($kabupaten);
    }
}
